CREATE TABLE [dbo].[Countries] (
[countryCode] char(2) NOT NULL default '',
[countryName] varchar(100) NOT NULL default '',
[img] varchar(512),
PRIMARY KEY ([countryCode])
);
-- 
-- Data
-- 
INSERT INTO [Countries] VALUES ('AF', 'Afghanistan', 'https://www.countryflags.io/AF/flat/64.png');
INSERT INTO [Countries] VALUES ('AL', 'Albania', 'https://www.countryflags.io/AL/flat/64.png');
INSERT INTO [Countries] VALUES ('DZ', 'Algeria', 'https://www.countryflags.io/DZ/flat/64.png');
INSERT INTO [Countries] VALUES ('DS', 'American Samoa', 'https://www.countryflags.io/DS/flat/64.png');
INSERT INTO [Countries] VALUES ('AD', 'Andorra', 'https://www.countryflags.io/AD/flat/64.png');
INSERT INTO [Countries] VALUES ('AO', 'Angola', 'https://www.countryflags.io/AO/flat/64.png');
INSERT INTO [Countries] VALUES ('AI', 'Anguilla', 'https://www.countryflags.io/AI/flat/64.png');
INSERT INTO [Countries] VALUES ('AQ', 'Antarctica', 'https://www.countryflags.io/AQ/flat/64.png');
INSERT INTO [Countries] VALUES ('AG', 'Antigua and Barbuda', 'https://www.countryflags.io/AG/flat/64.png');
INSERT INTO [Countries] VALUES ('AR', 'Argentina', 'https://www.countryflags.io/AR/flat/64.png');
INSERT INTO [Countries] VALUES ('AM', 'Armenia', 'https://www.countryflags.io/AM/flat/64.png');
INSERT INTO [Countries] VALUES ('AW', 'Aruba', 'https://www.countryflags.io/AW/flat/64.png');
INSERT INTO [Countries] VALUES ('AU', 'Australia', 'https://www.countryflags.io/AU/flat/64.png');
INSERT INTO [Countries] VALUES ('AT', 'Austria', 'https://www.countryflags.io/AT/flat/64.png');
INSERT INTO [Countries] VALUES ('AZ', 'Azerbaijan', 'https://www.countryflags.io/AZ/flat/64.png');
INSERT INTO [Countries] VALUES ('BS', 'Bahamas', 'https://www.countryflags.io/BS/flat/64.png');
INSERT INTO [Countries] VALUES ('BH', 'Bahrain', 'https://www.countryflags.io/BH/flat/64.png');
INSERT INTO [Countries] VALUES ('BD', 'Bangladesh', 'https://www.countryflags.io/BD/flat/64.png');
INSERT INTO [Countries] VALUES ('BB', 'Barbados', 'https://www.countryflags.io/BB/flat/64.png');
INSERT INTO [Countries] VALUES ('BY', 'Belarus', 'https://www.countryflags.io/BY/flat/64.png');
INSERT INTO [Countries] VALUES ('BE', 'Belgium', 'https://www.countryflags.io/BE/flat/64.png');
INSERT INTO [Countries] VALUES ('BZ', 'Belize', 'https://www.countryflags.io/BZ/flat/64.png');
INSERT INTO [Countries] VALUES ('BJ', 'Benin', 'https://www.countryflags.io/BJ/flat/64.png');
INSERT INTO [Countries] VALUES ('BM', 'Bermuda', 'https://www.countryflags.io/BM/flat/64.png');
INSERT INTO [Countries] VALUES ('BT', 'Bhutan', 'https://www.countryflags.io/BT/flat/64.png');
INSERT INTO [Countries] VALUES ('BO', 'Bolivia', 'https://www.countryflags.io/BO/flat/64.png');
INSERT INTO [Countries] VALUES ('BA', 'Bosnia and Herzegovina', 'https://www.countryflags.io/BA/flat/64.png');
INSERT INTO [Countries] VALUES ('BW', 'Botswana', 'https://www.countryflags.io/BW/flat/64.png');
INSERT INTO [Countries] VALUES ('BV', 'Bouvet Island', 'https://www.countryflags.io/BV/flat/64.png');
INSERT INTO [Countries] VALUES ('BR', 'Brazil', 'https://www.countryflags.io/BR/flat/64.png');
INSERT INTO [Countries] VALUES ('IO', 'British Indian Ocean Territory', 'https://www.countryflags.io/IO/flat/64.png');
INSERT INTO [Countries] VALUES ('BN', 'Brunei Darussalam', 'https://www.countryflags.io/BN/flat/64.png');
INSERT INTO [Countries] VALUES ('BG', 'Bulgaria', 'https://www.countryflags.io/BG/flat/64.png');
INSERT INTO [Countries] VALUES ('BF', 'Burkina Faso', 'https://www.countryflags.io/BF/flat/64.png');
INSERT INTO [Countries] VALUES ('BI', 'Burundi', 'https://www.countryflags.io/BI/flat/64.png');
INSERT INTO [Countries] VALUES ('KH', 'Cambodia', 'https://www.countryflags.io/KH/flat/64.png');
INSERT INTO [Countries] VALUES ('CM', 'Cameroon', 'https://www.countryflags.io/CM/flat/64.png');
INSERT INTO [Countries] VALUES ('CA', 'Canada', 'https://www.countryflags.io/CA/flat/64.png');
INSERT INTO [Countries] VALUES ('CV', 'Cape Verde', 'https://www.countryflags.io/CV/flat/64.png');
INSERT INTO [Countries] VALUES ('KY', 'Cayman Islands', 'https://www.countryflags.io/KY/flat/64.png');
INSERT INTO [Countries] VALUES ('CF', 'Central African Republic', 'https://www.countryflags.io/CF/flat/64.png');
INSERT INTO [Countries] VALUES ('TD', 'Chad', 'https://www.countryflags.io/TD/flat/64.png');
INSERT INTO [Countries] VALUES ('CL', 'Chile', 'https://www.countryflags.io/CL/flat/64.png');
INSERT INTO [Countries] VALUES ('CN', 'China', 'https://www.countryflags.io/CN/flat/64.png');
INSERT INTO [Countries] VALUES ('CX', 'Christmas Island', 'https://www.countryflags.io/CX/flat/64.png');
INSERT INTO [Countries] VALUES ('CC', 'Cocos (Keeling) Islands', 'https://www.countryflags.io/CC/flat/64.png');
INSERT INTO [Countries] VALUES ('CO', 'Colombia', 'https://www.countryflags.io/CO/flat/64.png');
INSERT INTO [Countries] VALUES ('KM', 'Comoros', 'https://www.countryflags.io/KM/flat/64.png');
INSERT INTO [Countries] VALUES ('CD', 'Democratic Republic of the Congo', 'https://www.countryflags.io/CD/flat/64.png');
INSERT INTO [Countries] VALUES ('CG', 'Republic of Congo', 'https://www.countryflags.io/CG/flat/64.png');
INSERT INTO [Countries] VALUES ('CK', 'Cook Islands', 'https://www.countryflags.io/CK/flat/64.png');
INSERT INTO [Countries] VALUES ('CR', 'Costa Rica', 'https://www.countryflags.io/CR/flat/64.png');
INSERT INTO [Countries] VALUES ('HR', 'Croatia (Hrvatska)', 'https://www.countryflags.io/HR/flat/64.png');
INSERT INTO [Countries] VALUES ('CU', 'Cuba', 'https://www.countryflags.io/CU/flat/64.png');
INSERT INTO [Countries] VALUES ('CY', 'Cyprus', 'https://www.countryflags.io/CY/flat/64.png');
INSERT INTO [Countries] VALUES ('CZ', 'Czech Republic', 'https://www.countryflags.io/CZ/flat/64.png');
INSERT INTO [Countries] VALUES ('DK', 'Denmark', 'https://www.countryflags.io/DK/flat/64.png');
INSERT INTO [Countries] VALUES ('DJ', 'Djibouti', 'https://www.countryflags.io/DJ/flat/64.png');
INSERT INTO [Countries] VALUES ('DM', 'Dominica', 'https://www.countryflags.io/DM/flat/64.png');
INSERT INTO [Countries] VALUES ('DO', 'Dominican Republic', 'https://www.countryflags.io/DO/flat/64.png');
INSERT INTO [Countries] VALUES ('TP', 'East Timor', 'https://www.countryflags.io/TP/flat/64.png');
INSERT INTO [Countries] VALUES ('EC', 'Ecuador', 'https://www.countryflags.io/EC/flat/64.png');
INSERT INTO [Countries] VALUES ('EG', 'Egypt', 'https://www.countryflags.io/EG/flat/64.png');
INSERT INTO [Countries] VALUES ('SV', 'El Salvador', 'https://www.countryflags.io/SV/flat/64.png');
INSERT INTO [Countries] VALUES ('GQ', 'Equatorial Guinea', 'https://www.countryflags.io/GQ/flat/64.png');
INSERT INTO [Countries] VALUES ('ER', 'Eritrea', 'https://www.countryflags.io/ER/flat/64.png');
INSERT INTO [Countries] VALUES ('EE', 'Estonia', 'https://www.countryflags.io/EE/flat/64.png');
INSERT INTO [Countries] VALUES ('ET', 'Ethiopia', 'https://www.countryflags.io/ET/flat/64.png');
INSERT INTO [Countries] VALUES ('FK', 'Falkland Islands (Malvinas)', 'https://www.countryflags.io/FK/flat/64.png');
INSERT INTO [Countries] VALUES ('FO', 'Faroe Islands', 'https://www.countryflags.io/FO/flat/64.png');
INSERT INTO [Countries] VALUES ('FJ', 'Fiji', 'https://www.countryflags.io/FJ/flat/64.png');
INSERT INTO [Countries] VALUES ('FI', 'Finland', 'https://www.countryflags.io/FI/flat/64.png');
INSERT INTO [Countries] VALUES ('FR', 'France', 'https://www.countryflags.io/FR/flat/64.png');
INSERT INTO [Countries] VALUES ('FX', 'France, Metropolitan', 'https://www.countryflags.io/FX/flat/64.png');
INSERT INTO [Countries] VALUES ('GF', 'French Guiana', 'https://www.countryflags.io/GF/flat/64.png');
INSERT INTO [Countries] VALUES ('PF', 'French Polynesia', 'https://www.countryflags.io/PF/flat/64.png');
INSERT INTO [Countries] VALUES ('TF', 'French Southern Territories', 'https://www.countryflags.io/TF/flat/64.png');
INSERT INTO [Countries] VALUES ('GA', 'Gabon', 'https://www.countryflags.io/GA/flat/64.png');
INSERT INTO [Countries] VALUES ('GM', 'Gambia', 'https://www.countryflags.io/GM/flat/64.png');
INSERT INTO [Countries] VALUES ('GE', 'Georgia', 'https://www.countryflags.io/GE/flat/64.png');
INSERT INTO [Countries] VALUES ('DE', 'Germany', 'https://www.countryflags.io/DE/flat/64.png');
INSERT INTO [Countries] VALUES ('GH', 'Ghana', 'https://www.countryflags.io/GH/flat/64.png');
INSERT INTO [Countries] VALUES ('GI', 'Gibraltar', 'https://www.countryflags.io/GI/flat/64.png');
INSERT INTO [Countries] VALUES ('GK', 'Guernsey', 'https://www.countryflags.io/GK/flat/64.png');
INSERT INTO [Countries] VALUES ('GR', 'Greece', 'https://www.countryflags.io/GR/flat/64.png');
INSERT INTO [Countries] VALUES ('GL', 'Greenland', 'https://www.countryflags.io/GL/flat/64.png');
INSERT INTO [Countries] VALUES ('GD', 'Grenada', 'https://www.countryflags.io/AF/flat/64.png');
INSERT INTO [Countries] VALUES ('GP', 'Guadeloupe', 'https://www.countryflags.io/GP/flat/64.png');
INSERT INTO [Countries] VALUES ('GU', 'Guam', 'https://www.countryflags.io/GU/flat/64.png');
INSERT INTO [Countries] VALUES ('GT', 'Guatemala', 'https://www.countryflags.io/GT/flat/64.png');
INSERT INTO [Countries] VALUES ('GN', 'Guinea', 'https://www.countryflags.io/GN/flat/64.png');
INSERT INTO [Countries] VALUES ('GW', 'Guinea-Bissau', 'https://www.countryflags.io/GW/flat/64.png');
INSERT INTO [Countries] VALUES ('GY', 'Guyana', 'https://www.countryflags.io/GY/flat/64.png');
INSERT INTO [Countries] VALUES ('HT', 'Haiti', 'https://www.countryflags.io/HT/flat/64.png');
INSERT INTO [Countries] VALUES ('HM', 'Heard and Mc Donald Islands', 'https://www.countryflags.io/HM/flat/64.png');
INSERT INTO [Countries] VALUES ('HN', 'Honduras', 'https://www.countryflags.io/HN/flat/64.png');
INSERT INTO [Countries] VALUES ('HK', 'Hong Kong', 'https://www.countryflags.io/HK/flat/64.png');
INSERT INTO [Countries] VALUES ('HU', 'Hungary', 'https://www.countryflags.io/HU/flat/64.png');
INSERT INTO [Countries] VALUES ('IS', 'Iceland', 'https://www.countryflags.io/IS/flat/64.png');
INSERT INTO [Countries] VALUES ('IN', 'India', 'https://www.countryflags.io/IN/flat/64.png');
INSERT INTO [Countries] VALUES ('IM', 'Isle of Man', 'https://www.countryflags.io/IM/flat/64.png');
INSERT INTO [Countries] VALUES ('ID', 'Indonesia', 'https://www.countryflags.io/ID/flat/64.png');
INSERT INTO [Countries] VALUES ('IR', 'Iran (Islamic Republic of)', 'https://www.countryflags.io/IR/flat/64.png');
INSERT INTO [Countries] VALUES ('IQ', 'Iraq', 'https://www.countryflags.io/IQ/flat/64.png');
INSERT INTO [Countries] VALUES ('IE', 'Ireland', 'https://www.countryflags.io/IE/flat/64.png');
INSERT INTO [Countries] VALUES ('IL', 'Israel', 'https://www.countryflags.io/IL/flat/64.png');
INSERT INTO [Countries] VALUES ('IT', 'Italy', 'https://www.countryflags.io/IT/flat/64.png');
INSERT INTO [Countries] VALUES ('CI', 'Ivory Coast', 'https://www.countryflags.io/CI/flat/64.png');
INSERT INTO [Countries] VALUES ('JE', 'Jersey', 'https://www.countryflags.io/JE/flat/64.png');
INSERT INTO [Countries] VALUES ('JM', 'Jamaica', 'https://www.countryflags.io/JM/flat/64.png');
INSERT INTO [Countries] VALUES ('JP', 'Japan', 'https://www.countryflags.io/JP/flat/64.png');
INSERT INTO [Countries] VALUES ('JO', 'Jordan', 'https://www.countryflags.io/JO/flat/64.png');
INSERT INTO [Countries] VALUES ('KZ', 'Kazakhstan', 'https://www.countryflags.io/KZ/flat/64.png');
INSERT INTO [Countries] VALUES ('KE', 'Kenya', 'https://www.countryflags.io/KE/flat/64.png');
INSERT INTO [Countries] VALUES ('KI', 'Kiribati', 'https://www.countryflags.io/KI/flat/64.png');
INSERT INTO [Countries] VALUES ('KP', 'Korea, Democratic People''s Republic of', 'https://www.countryflags.io/KP/flat/64.png');
INSERT INTO [Countries] VALUES ('KR', 'Korea, Republic of', 'https://www.countryflags.io/KR/flat/64.png');
INSERT INTO [Countries] VALUES ('XK', 'Kosovo', 'https://www.countryflags.io/XK/flat/64.png');
INSERT INTO [Countries] VALUES ('KW', 'Kuwait', 'https://www.countryflags.io/KW/flat/64.png');
INSERT INTO [Countries] VALUES ('KG', 'Kyrgyzstan', 'https://www.countryflags.io/KG/flat/64.png');
INSERT INTO [Countries] VALUES ('LA', 'Lao People''s Democratic Republic', 'https://www.countryflags.io/LA/flat/64.png');
INSERT INTO [Countries] VALUES ('LV', 'Latvia', 'https://www.countryflags.io/LV/flat/64.png');
INSERT INTO [Countries] VALUES ('LB', 'Lebanon', 'https://www.countryflags.io/LB/flat/64.png');
INSERT INTO [Countries] VALUES ('LS', 'Lesotho', 'https://www.countryflags.io/LS/flat/64.png');
INSERT INTO [Countries] VALUES ('LR', 'Liberia', 'https://www.countryflags.io/LR/flat/64.png');
INSERT INTO [Countries] VALUES ('LY', 'Libyan Arab Jamahiriya', 'https://www.countryflags.io/LY/flat/64.png');
INSERT INTO [Countries] VALUES ('LI', 'Liechtenstein', 'https://www.countryflags.io/LI/flat/64.png');
INSERT INTO [Countries] VALUES ('LT', 'Lithuania', 'https://www.countryflags.io/LT/flat/64.png');
INSERT INTO [Countries] VALUES ('LU', 'Luxembourg', 'https://www.countryflags.io/LU/flat/64.png');
INSERT INTO [Countries] VALUES ('MO', 'Macau', 'https://www.countryflags.io/MO/flat/64.png');
INSERT INTO [Countries] VALUES ('MK', 'North Macedonia', 'https://www.countryflags.io/MK/flat/64.png');
INSERT INTO [Countries] VALUES ('MG', 'Madagascar', 'https://www.countryflags.io/MG/flat/64.png');
INSERT INTO [Countries] VALUES ('MW', 'Malawi', 'https://www.countryflags.io/MW/flat/64.png');
INSERT INTO [Countries] VALUES ('MY', 'Malaysia', 'https://www.countryflags.io/MY/flat/64.png');
INSERT INTO [Countries] VALUES ('MV', 'Maldives', 'https://www.countryflags.io/MV/flat/64.png');
INSERT INTO [Countries] VALUES ('ML', 'Mali', 'https://www.countryflags.io/ML/flat/64.png');
INSERT INTO [Countries] VALUES ('MT', 'Malta', 'https://www.countryflags.io/MT/flat/64.png');
INSERT INTO [Countries] VALUES ('MH', 'Marshall Islands', 'https://www.countryflags.io/MH/flat/64.png');
INSERT INTO [Countries] VALUES ('MQ', 'Martinique', 'https://www.countryflags.io/MQ/flat/64.png');
INSERT INTO [Countries] VALUES ('MR', 'Mauritania', 'https://www.countryflags.io/MR/flat/64.png');
INSERT INTO [Countries] VALUES ('MU', 'Mauritius', 'https://www.countryflags.io/MU/flat/64.png');
INSERT INTO [Countries] VALUES ('TY', 'Mayotte', 'https://www.countryflags.io/TY/flat/64.png');
INSERT INTO [Countries] VALUES ('MX', 'Mexico', 'https://www.countryflags.io/MX/flat/64.png');
INSERT INTO [Countries] VALUES ('FM', 'Micronesia, Federated States of', 'https://www.countryflags.io/FM/flat/64.png');
INSERT INTO [Countries] VALUES ('MD', 'Moldova, Republic of', 'https://www.countryflags.io/MD/flat/64.png');
INSERT INTO [Countries] VALUES ('MC', 'Monaco', 'https://www.countryflags.io/MC/flat/64.png');
INSERT INTO [Countries] VALUES ('MN', 'Mongolia', 'https://www.countryflags.io/MN/flat/64.png');
INSERT INTO [Countries] VALUES ('ME', 'Montenegro', 'https://www.countryflags.io/ME/flat/64.png');
INSERT INTO [Countries] VALUES ('MS', 'Montserrat', 'https://www.countryflags.io/MS/flat/64.png');
INSERT INTO [Countries] VALUES ('MA', 'Morocco', 'https://www.countryflags.io/MA/flat/64.png');
INSERT INTO [Countries] VALUES ('MZ', 'Mozambique', 'https://www.countryflags.io/MZ/flat/64.png');
INSERT INTO [Countries] VALUES ('MM', 'Myanmar', 'https://www.countryflags.io/MM/flat/64.png');
INSERT INTO [Countries] VALUES ('NA', 'Namibia', 'https://www.countryflags.io/NA/flat/64.png');
INSERT INTO [Countries] VALUES ('NR', 'Nauru', 'https://www.countryflags.io/NR/flat/64.png');
INSERT INTO [Countries] VALUES ('NP', 'Nepal', 'https://www.countryflags.io/NP/flat/64.png');
INSERT INTO [Countries] VALUES ('NL', 'Netherlands', 'https://www.countryflags.io/NL/flat/64.png');
INSERT INTO [Countries] VALUES ('AN', 'Netherlands Antilles', 'https://www.countryflags.io/AN/flat/64.png');
INSERT INTO [Countries] VALUES ('NC', 'New Caledonia', 'https://www.countryflags.io/NC/flat/64.png');
INSERT INTO [Countries] VALUES ('NZ', 'New Zealand', 'https://www.countryflags.io/NZ/flat/64.png');
INSERT INTO [Countries] VALUES ('NI', 'Nicaragua', 'https://www.countryflags.io/NI/flat/64.png');
INSERT INTO [Countries] VALUES ('NE', 'Niger', 'https://www.countryflags.io/NE/flat/64.png');
INSERT INTO [Countries] VALUES ('NG', 'Nigeria', 'https://www.countryflags.io/NG/flat/64.png');
INSERT INTO [Countries] VALUES ('NU', 'Niue', 'https://www.countryflags.io/NU/flat/64.png');
INSERT INTO [Countries] VALUES ('NF', 'Norfolk Island', 'https://www.countryflags.io/NF/flat/64.png');
INSERT INTO [Countries] VALUES ('MP', 'Northern Mariana Islands', 'https://www.countryflags.io/MP/flat/64.png');
INSERT INTO [Countries] VALUES ('NO', 'Norway', 'https://www.countryflags.io/NO/flat/64.png');
INSERT INTO [Countries] VALUES ('OM', 'Oman', 'https://www.countryflags.io/OM/flat/64.png');
INSERT INTO [Countries] VALUES ('PK', 'Pakistan', 'https://www.countryflags.io/PK/flat/64.png');
INSERT INTO [Countries] VALUES ('PW', 'Palau', 'https://www.countryflags.io/PW/flat/64.png');
INSERT INTO [Countries] VALUES ('PS', 'Palestine', 'https://www.countryflags.io/PS/flat/64.png');
INSERT INTO [Countries] VALUES ('PA', 'Panama', 'https://www.countryflags.io/PA/flat/64.png');
INSERT INTO [Countries] VALUES ('PG', 'Papua New Guinea', 'https://www.countryflags.io/PG/flat/64.png');
INSERT INTO [Countries] VALUES ('PY', 'Paraguay', 'https://www.countryflags.io/PY/flat/64.png');
INSERT INTO [Countries] VALUES ('PE', 'Peru', 'https://www.countryflags.io/PE/flat/64.png');
INSERT INTO [Countries] VALUES ('PH', 'Philippines', 'https://www.countryflags.io/PH/flat/64.png');
INSERT INTO [Countries] VALUES ('PN', 'Pitcairn', 'https://www.countryflags.io/PN/flat/64.png');
INSERT INTO [Countries] VALUES ('PL', 'Poland', 'https://www.countryflags.io/PL/flat/64.png');
INSERT INTO [Countries] VALUES ('PT', 'Portugal', 'https://www.countryflags.io/PT/flat/64.png');
INSERT INTO [Countries] VALUES ('PR', 'Puerto Rico', 'https://www.countryflags.io/PR/flat/64.png');
INSERT INTO [Countries] VALUES ('QA', 'Qatar', 'https://www.countryflags.io/QA/flat/64.png');
INSERT INTO [Countries] VALUES ('RE', 'Reunion', 'https://www.countryflags.io/RE/flat/64.png');
INSERT INTO [Countries] VALUES ('RO', 'Romania', 'https://www.countryflags.io/RO/flat/64.png');
INSERT INTO [Countries] VALUES ('RU', 'Russian Federation', 'https://www.countryflags.io/RU/flat/64.png');
INSERT INTO [Countries] VALUES ('RW', 'Rwanda', 'https://www.countryflags.io/RW/flat/64.png');
INSERT INTO [Countries] VALUES ('KN', 'Saint Kitts and Nevis', 'https://www.countryflags.io/KN/flat/64.png');
INSERT INTO [Countries] VALUES ('LC', 'Saint Lucia', 'https://www.countryflags.io/LC/flat/64.png');
INSERT INTO [Countries] VALUES ('VC', 'Saint Vincent and the Grenadines', 'https://www.countryflags.io/VC/flat/64.png');
INSERT INTO [Countries] VALUES ('WS', 'Samoa', 'https://www.countryflags.io/WS/flat/64.png');
INSERT INTO [Countries] VALUES ('SM', 'San Marino', 'https://www.countryflags.io/SM/flat/64.png');
INSERT INTO [Countries] VALUES ('ST', 'Sao Tome and Principe', 'https://www.countryflags.io/ST/flat/64.png');
INSERT INTO [Countries] VALUES ('SA', 'Saudi Arabia', 'https://www.countryflags.io/SA/flat/64.png');
INSERT INTO [Countries] VALUES ('SN', 'Senegal', 'https://www.countryflags.io/SN/flat/64.png');
INSERT INTO [Countries] VALUES ('RS', 'Serbia', 'https://www.countryflags.io/RS/flat/64.png');
INSERT INTO [Countries] VALUES ('SC', 'Seychelles', 'https://www.countryflags.io/SC/flat/64.png');
INSERT INTO [Countries] VALUES ('SL', 'Sierra Leone', 'https://www.countryflags.io/SL/flat/64.png');
INSERT INTO [Countries] VALUES ('SG', 'Singapore', 'https://www.countryflags.io/SG/flat/64.png');
INSERT INTO [Countries] VALUES ('SK', 'Slovakia', 'https://www.countryflags.io/SK/flat/64.png');
INSERT INTO [Countries] VALUES ('SI', 'Slovenia', 'https://www.countryflags.io/SI/flat/64.png');
INSERT INTO [Countries] VALUES ('SB', 'Solomon Islands', 'https://www.countryflags.io/SB/flat/64.png');
INSERT INTO [Countries] VALUES ('SO', 'Somalia', 'https://www.countryflags.io/SO/flat/64.png');
INSERT INTO [Countries] VALUES ('ZA', 'South Africa', 'https://www.countryflags.io/ZA/flat/64.png');
INSERT INTO [Countries] VALUES ('GS', 'South Georgia South Sandwich Islands', 'https://www.countryflags.io/GS/flat/64.png');
INSERT INTO [Countries] VALUES ('SS', 'South Sudan', 'https://www.countryflags.io/SS/flat/64.png');
INSERT INTO [Countries] VALUES ('ES', 'Spain', 'https://www.countryflags.io/ES/flat/64.png');
INSERT INTO [Countries] VALUES ('LK', 'Sri Lanka', 'https://www.countryflags.io/LK/flat/64.png');
INSERT INTO [Countries] VALUES ('SH', 'St. Helena', 'https://www.countryflags.io/SH/flat/64.png');
INSERT INTO [Countries] VALUES ('PM', 'St. Pierre and Miquelon', 'https://www.countryflags.io/PM/flat/64.png');
INSERT INTO [Countries] VALUES ('SD', 'Sudan', 'https://www.countryflags.io/SD/flat/64.png');
INSERT INTO [Countries] VALUES ('SR', 'Suriname', 'https://www.countryflags.io/SR/flat/64.png');
INSERT INTO [Countries] VALUES ('SJ', 'Svalbard and Jan Mayen Islands', 'https://www.countryflags.io/SJ/flat/64.png');
INSERT INTO [Countries] VALUES ('SZ', 'Swaziland', 'https://www.countryflags.io/SZ/flat/64.png');
INSERT INTO [Countries] VALUES ('SE', 'Sweden', 'https://www.countryflags.io/SE/flat/64.png');
INSERT INTO [Countries] VALUES ('CH', 'Switzerland', 'https://www.countryflags.io/CH/flat/64.png');
INSERT INTO [Countries] VALUES ('SY', 'Syrian Arab Republic', 'https://www.countryflags.io/SY/flat/64.png');
INSERT INTO [Countries] VALUES ('TW', 'Taiwan', 'https://www.countryflags.io/TW/flat/64.png');
INSERT INTO [Countries] VALUES ('TJ', 'Tajikistan', 'https://www.countryflags.io/TJ/flat/64.png');
INSERT INTO [Countries] VALUES ('TZ', 'Tanzania, United Republic of', 'https://www.countryflags.io/TZ/flat/64.png');
INSERT INTO [Countries] VALUES ('TH', 'Thailand', 'https://www.countryflags.io/TH/flat/64.png');
INSERT INTO [Countries] VALUES ('TG', 'Togo', 'https://www.countryflags.io/TG/flat/64.png');
INSERT INTO [Countries] VALUES ('TK', 'Tokelau', 'https://www.countryflags.io/TK/flat/64.png');
INSERT INTO [Countries] VALUES ('TO', 'Tonga', 'https://www.countryflags.io/TO/flat/64.png');
INSERT INTO [Countries] VALUES ('TT', 'Trinidad and Tobago', 'https://www.countryflags.io/TT/flat/64.png');
INSERT INTO [Countries] VALUES ('TN', 'Tunisia', 'https://www.countryflags.io/TN/flat/64.png');
INSERT INTO [Countries] VALUES ('TR', 'Turkey', 'https://www.countryflags.io/TR/flat/64.png');
INSERT INTO [Countries] VALUES ('TM', 'Turkmenistan', 'https://www.countryflags.io/TM/flat/64.png');
INSERT INTO [Countries] VALUES ('TC', 'Turks and Caicos Islands', 'https://www.countryflags.io/TC/flat/64.png');
INSERT INTO [Countries] VALUES ('TV', 'Tuvalu', 'https://www.countryflags.io/TV/flat/64.png');
INSERT INTO [Countries] VALUES ('UG', 'Uganda', 'https://www.countryflags.io/UG/flat/64.png');
INSERT INTO [Countries] VALUES ('UA', 'Ukraine', 'https://www.countryflags.io/UA/flat/64.png');
INSERT INTO [Countries] VALUES ('AE', 'United Arab Emirates', 'https://www.countryflags.io/AE/flat/64.png');
INSERT INTO [Countries] VALUES ('GB', 'United Kingdom', 'https://www.countryflags.io/GB/flat/64.png');
INSERT INTO [Countries] VALUES ('US', 'United States', 'https://www.countryflags.io/US/flat/64.png');
INSERT INTO [Countries] VALUES ('UM', 'United States minor outlying islands', 'https://www.countryflags.io/UM/flat/64.png');
INSERT INTO [Countries] VALUES ('UY', 'Uruguay', 'https://www.countryflags.io/UY/flat/64.png');
INSERT INTO [Countries] VALUES ('UZ', 'Uzbekistan', 'https://www.countryflags.io/UZ/flat/64.png');
INSERT INTO [Countries] VALUES ('VU', 'Vanuatu', 'https://www.countryflags.io/VU/flat/64.png');
INSERT INTO [Countries] VALUES ('VA', 'Vatican City State', 'https://www.countryflags.io/VA/flat/64.png');
INSERT INTO [Countries] VALUES ('VE', 'Venezuela', 'https://www.countryflags.io/VE/flat/64.png');
INSERT INTO [Countries] VALUES ('VN', 'Vietnam', 'https://www.countryflags.io/VN/flat/64.png');
INSERT INTO [Countries] VALUES ('VG', 'Virgin Islands (British)', 'https://www.countryflags.io/VG/flat/64.png');
INSERT INTO [Countries] VALUES ('VI', 'Virgin Islands (U.S.)', 'https://www.countryflags.io/VI/flat/64.png');
INSERT INTO [Countries] VALUES ('WF', 'Wallis and Futuna Islands', 'https://www.countryflags.io/WF/flat/64.png');
INSERT INTO [Countries] VALUES ('EH', 'Western Sahara', 'https://www.countryflags.io/EH/flat/64.png');
INSERT INTO [Countries] VALUES ('YE', 'Yemen', 'https://www.countryflags.io/YE/flat/64.png');
INSERT INTO [Countries] VALUES ('ZM', 'Zambia', 'https://www.countryflags.io/ZM/flat/64.png');
INSERT INTO [Countries] VALUES ('ZW', 'Zimbabwe', 'https://www.countryflags.io/ZW/flat/64.png');